// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvA8LfhHjFhlTusw9ZKhunj8cisaGHq8g',
    appId: '1:203780219336:web:7d596891385a7583fc20fd',
    messagingSenderId: '203780219336',
    projectId: 'who-s-next-dd97b',
    authDomain: 'who-s-next-dd97b.firebaseapp.com',
    storageBucket: 'who-s-next-dd97b.appspot.com',
    measurementId: 'G-L55QBD8LHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmh8BdEJpn7_i8HXVglzMsnNGjYSEM_xk',
    appId: '1:203780219336:android:4e8e2eeeee6218aefc20fd',
    messagingSenderId: '203780219336',
    projectId: 'who-s-next-dd97b',
    storageBucket: 'who-s-next-dd97b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKEwlZGgkeC9ssGNPvKOpfwWpnh0rJwy0',
    appId: '1:203780219336:ios:3b47c8d4d5e92ac0fc20fd',
    messagingSenderId: '203780219336',
    projectId: 'who-s-next-dd97b',
    storageBucket: 'who-s-next-dd97b.appspot.com',
    iosClientId: '203780219336-tffna0q7p3mf5dsfs4nhsomm4octndrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whosnext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKEwlZGgkeC9ssGNPvKOpfwWpnh0rJwy0',
    appId: '1:203780219336:ios:3b47c8d4d5e92ac0fc20fd',
    messagingSenderId: '203780219336',
    projectId: 'who-s-next-dd97b',
    storageBucket: 'who-s-next-dd97b.appspot.com',
    iosClientId: '203780219336-tffna0q7p3mf5dsfs4nhsomm4octndrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whosnext',
  );
}
